# Generated by Django 6.0.4 on 2026-04-19 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='DataZen Analytics', max_length=200)),
                ('tagline', models.CharField(blank=True, max_length=500)),
                ('company_description', models.TextField(help_text='Main description about the company')),
                ('mission', models.TextField(help_text='Company mission statement')),
                ('vision', models.TextField(help_text='Company vision statement')),
                ('established_year', models.IntegerField(default=2019)),
                ('team_size', models.CharField(default='15+', max_length=100)),
                ('company_values', models.TextField(blank=True, help_text='Core values (one per line)')),
                ('about_image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('founded_by', models.CharField(blank=True, max_length=200)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('office_address', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Page',
                'verbose_name_plural': 'About Page',
            },
        ),
    ]
