# Generated by Django 5.2.7 on 2026-04-27 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_salesinquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinquiry',
            name='company',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='salesinquiry',
            name='inquiry_type',
            field=models.CharField(choices=[('call', 'Phone Call'), ('email', 'Email Inquiry'), ('contact_form', 'Contact Form')], default='contact_form', max_length=20),
        ),
        migrations.AddField(
            model_name='salesinquiry',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salesinquiry',
            name='name',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
    ]
