# Generated by Django 5.2.7 on 2026-04-27 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_salesinquiry_company_salesinquiry_inquiry_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesinquiry',
            options={'ordering': ['-created_at'], 'verbose_name': 'Sales Inquiry', 'verbose_name_plural': 'Sales Inquiries'},
        ),
        migrations.AlterField(
            model_name='salesinquiry',
            name='company_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='salesinquiry',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='salesinquiry',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='salesinquiry',
            name='plan',
            field=models.CharField(choices=[('starter', 'Starter'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], default='starter', max_length=20),
        ),
        migrations.AlterField(
            model_name='salesinquiry',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_inquiries', to=settings.AUTH_USER_MODEL),
        ),
    ]
