# Generated by Django 5.2.7 on 2026-04-27 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_salesinquiry_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinquiry',
            name='reply',
            field=models.TextField(blank=True, help_text='Reply message to send to the customer', null=True),
        ),
        migrations.AddField(
            model_name='salesinquiry',
            name='reply_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salesinquiry',
            name='reply_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
