# Generated by Django 5.2.7 on 2026-04-27 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_salesinquiry_reply_salesinquiry_reply_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='cofounder_bio',
            field=models.TextField(blank=True, help_text='Co-Founder biography', null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='cofounder_image',
            field=models.ImageField(blank=True, null=True, upload_to='about/'),
        ),
        migrations.AddField(
            model_name='about',
            name='cofounder_name',
            field=models.CharField(blank=True, help_text='Co-Founder name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='cofounder_title',
            field=models.CharField(blank=True, default='Co-Founder', max_length=200, null=True),
        ),
    ]
