# Generated by Django 5.2.7 on 2026-04-27 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_about_cofounder_bio_about_cofounder_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='founder_bio',
            field=models.TextField(blank=True, help_text="Founder's biography", null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='founder_title',
            field=models.CharField(blank=True, default='Founder & CEO', help_text="Founder's title", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='about_image',
            field=models.ImageField(blank=True, help_text="Founder's photo", null=True, upload_to='about/'),
        ),
        migrations.AlterField(
            model_name='about',
            name='founded_by',
            field=models.CharField(blank=True, help_text="Founder's name", max_length=200),
        ),
    ]
