# Generated by Django 5.2.7 on 2026-05-03 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_contact_options_remove_contact_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='reply_seen',
            field=models.BooleanField(default=False, help_text='Has the user seen the reply?'),
        ),
    ]
