# Generated by Django 5.2.7 on 2026-05-03 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Internal admin notes about this subscriber', null=True),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='last_email_sent',
            field=models.DateTimeField(blank=True, help_text='When was the last newsletter sent to this subscriber?', null=True),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='name',
            field=models.CharField(blank=True, help_text='Subscriber name (optional)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='source',
            field=models.CharField(choices=[('blog', 'Blog Page'), ('homepage', 'Homepage'), ('manual', 'Manual Entry'), ('import', 'Imported'), ('contact_form', 'Contact Form'), ('other', 'Other')], default='other', help_text='How did they subscribe?', max_length=20),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='unsubscribe_reason',
            field=models.TextField(blank=True, help_text='Reason for unsubscribing', null=True),
        ),
        migrations.AddIndex(
            model_name='newsletter',
            index=models.Index(fields=['is_active', '-subscribed_date'], name='main_newsle_is_acti_a501e5_idx'),
        ),
        migrations.AddIndex(
            model_name='newsletter',
            index=models.Index(fields=['email'], name='main_newsle_email_847fdb_idx'),
        ),
    ]
