# Generated by Django 5.2.7 on 2026-05-04 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_blogpost_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='source',
            field=models.CharField(choices=[('blog', 'Blog Page'), ('user_login', 'User Login Page'), ('homepage', 'Homepage'), ('manual', 'Manual Entry'), ('import', 'Imported'), ('contact_form', 'Contact Form'), ('other', 'Other')], default='other', help_text='How did they subscribe?', max_length=20),
        ),
    ]
